# Generated by Django 4.1.7 on 2023-03-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moviereview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channelname', models.CharField(max_length=255)),
                ('movie', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('hero', models.CharField(max_length=255)),
                ('heroine', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mymodelresults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=255)),
                ('total_comments', models.IntegerField()),
                ('total_positive_comments', models.IntegerField()),
                ('total_negative_comments', models.IntegerField()),
                ('final_verdict', models.CharField(max_length=255)),
            ],
        ),
    ]
